/*
   CREATE TABLE products (
       id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
       model  varchar(30) NOT NULL,
       company varchar(30) NOT NULL,
       price integer NOT NULL
   );
*/

package main

import (
	"database/sql"
	"fmt"

	_ "github.com/lib/pq"
)

func main() {
	conn := "user=postgres password=password dbname=productdb sslmode=disable"
	db, err := sql.Open("postgres", conn)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	result, err := db.Exec("insert into products (model, company, price) values ('iPhone X', $1, $2)", "Apple", 1000)
	if err != nil {
		panic(err)
	}
	fmt.Println(result.LastInsertId())
	fmt.Println(result.RowsAffected())
}
